name: CI

on: [push] # O robô acorda em todo Push

jobs:
  run-tests:
    runs-on: ubuntu-latest # Roda numa máquina Linux virtual do GitHub

    steps:
      - uses: actions/checkout@v3 # 1. Baixa seu código

      - name: Install Node.js
        uses: actions/setup-node@v3 # 2. Instala o Node
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci # 3. Instala os pacotes (npm ci é mais rápido e seguro que npm i)

      - name: Run Unit Tests
        run: npm test # 4. Roda os testes (Vitest)
